### ISSUE TITLE
Troubleshoot guide for errors "CORS/Cross-Origin Request Blocked", "429 - Too Many Requests", "503 - Haven't found your country code yet"

### ISSUE THREAD

**Issue by bryanseah234** [jvloo/popcat-popbot#1]
hi there, love yr work, just tried it out but the console throws me this error as attached in screenshot

![image](https://user-images.githubusercontent.com/66017805/129481167-7ae5ae9e-db6c-441c-aeab-546266579a9a.png)

please advice, thankyou

**Comment by bryanseah234** [comment]
Failed due to error 429 - Too Many Requests. Retrying..

**Comment by jvloo** [comment]
> hi there, love yr work, just tried it out but the console throws me this error as attached in screenshot
> 
> ![image](https://user-images.githubusercontent.com/66017805/129481167-7ae5ae9e-db6c-441c-aeab-546266579a9a.png)
> 
> please advice, thankyou

Hi, as for the CORS error, it's present on the ''leaderboard.popcat.click'', which is used for loading the leaderboard scores, and not related to the click API ''stats.popcat.click''. You can just ignore the error.

In order to check whether your API request (clicks) is accepted, just tap ''F12'' to open devtools and navigate to ''Network'' tab.

You may check those lines starting with ''pop?pop_count=800.....'' and check the status for value ''200'' or ''201''. Other than those two values, indicates a rejected request (whole line present as red text).

A rejected request may return status,  such as ''CORS'',  ''500''  and  ''429''.  You can just ignore them if it's not appear frequently  (more ''200'' or  ''201''  status present).

If you spot that the rejected request appears very frequent, you may try to:
1. Reconnect wifi on you device
2. Clear browser cookie & refresh PopCat website
3. Run again the script

If the error still persist, you might need to stop for 12 hours (Some claimed that this happens because your IP address has been blocked by the server for 12 hours).

Please do let me know if you still can't resolve your issue.

**Comment by jvloo** [comment]
You may use the console search bar to filter out only relevant API requests. Just type ''pop_count'' as the keyword.

A normal condition may only have a few or none of the error line (in red text):

<img src="https://user-images.githubusercontent.com/54534702/129489256-e9c20e6a-b0c6-4bb3-8f9d-70abe9f3a54c.png">

**Comment by jvloo** [comment]
> Failed due to error 429 - Too Many Requests. Retrying..

Make sure you only run the script on one browser tab per device. The API request is restricted per IP address, and you will get 429 error (too many request) frequently if you do.

**Comment by zeroryuki** [comment]
> > Failed due to error 429 - Too Many Requests. Retrying..
> 
> Make sure you only run the script on one browser tab per device. The API request is restricted per IP address, and you will get 429 error (too many request) frequently if you do.

tested with request every 28 seconds, no issue.. lower than that, will hit 429 error code. and seems it just check the ip and frequency. appended the recaptcha_token with any random string every 28 seconds success as well

**Comment by jvloo** [comment]
> > > Failed due to error 429 - Too Many Requests. Retrying..
> > 
> > 
> > Make sure you only run the script on one browser tab per device. The API request is restricted per IP address, and you will get 429 error (too many request) frequently if you do.
> 
> tested with request every 28 seconds, no issue.. lower than that, will hit 429 error code. and seems it just check the ip and frequency. appended the recaptcha_token with any random string every 28 seconds success as well

I think it also depends on the wifi. Me & my friends running on our house wifi (Maxis), not getting any (or seldom) 429 error over 24 hours 🤣

12k plus API requests sent:

<img src="https://user-images.githubusercontent.com/54534702/129516769-5865e11b-b0bc-4071-9298-1ca4cd4bd6be.jpg" width="70%">

**Comment by bryanseah234** [comment]
> 
> 
> > > > Failed due to error 429 - Too Many Requests. Retrying..
> > > 
> > > 
> > > Make sure you only run the script on one browser tab per device. The API request is restricted per IP address, and you will get 429 error (too many request) frequently if you do.
> > 
> > 
> > tested with request every 28 seconds, no issue.. lower than that, will hit 429 error code. and seems it just check the ip and frequency. appended the recaptcha_token with any random string every 28 seconds success as well
> 
> I think it also depends on the wifi. Me & my friends running on our house wifi (Maxis), not getting any (or seldom) 429 error over 24 hours 🤣
> 
> 12k plus API requests sent:
> 
> <img alt="" width="70%" src="https://user-images.githubusercontent.com/54534702/129516769-5865e11b-b0bc-4071-9298-1ca4cd4bd6be.jpg">

woahhh hahha noiceee.. thankyou for your reply!

**Comment by bryanseah234** [comment]
i'll close this issue now, thankyou again

**Comment by jvloo** [comment]
**Why Popcat is throwing 503 errors?**

Popcat will sometimes respond with an error "503 - Haven't found your country code yet (try again later)". Despite what the error describing, it is most likely not to do with detecting your country, but rather CloudFlare have flagged you as a bot, and the API call failed. Unfortunately, you might need to wait it out.

AdBlocker is known to cause issue as well, simply disable them and see if it works.

Reference: https://github.com/MokuMoki/PopHub#why-popcat-is-throwing-503-errors
